name: Sync, Translate and Deploy

on:
  schedule:
    - cron: '*/30 * * * *' # every 30 minutes
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # on button click

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.5
      - name: Merge upstream
        run: |
          git config --global user.name 'name'
          git config --global user.email 'name@email.com'
          git pull --unshallow
          git remote add upstream https://github.com/wuxian-space/docs-test.git
          git fetch upstream
          git checkout main
          git merge --no-edit upstream/main
          git push origin main
          git fetch upstream --tags
          git push --tags

  translate:
    needs: sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Clone translation tool (if needed)
        run: |
          git clone $AITDOCS_REPO
          cd aitdocs

      - name: Setup environment variables
        run: |
          echo "ALI_BASE_URL=$ALI_LLM_BASE_URL" > .env
          echo "ALI_MODEL_NAME=$ALI_LLM_MODEL_NAME" >> .env
          echo "ALI_API_KEY=${{secrets.ALI_LLM_API_KEY}}" >> .env

      - name: Setup uv
        uses: astral-sh/setup-uv@v6.4.3
        with:
          version: latest
          activate-environment: true # 激活虚拟环境
          working-directory: . # 项目根目录

      - name: Run translation
        run: |
          uv sync --frozen
          uv run main.py -d $DOCS_DIR  --incremental --auto-commit --auto-push
