name: Sync, Translate and Deploy

on:
  schedule:
    - cron: '*/30 * * * *' # every 30 minutes
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # on button click

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v2.0
        with:
          token: ${{ secrets.FORK_SYNC_TOKEN }}
          base: main
          head: main

  translate:
    needs: sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Clone translation tool (if needed)
        run: |
          git clone ${{vars.AITDOCS_REPO}}
          ls
          cd aitdocs
          ls

      - name: Setup environment variables
        run: |
          echo "ALI_BASE_URL=${{vars.ALI_LLM_BASE_URL}}" > .env
          echo "ALI_MODEL_NAME=${{vars.ALI_LLM_MODEL_NAME}}" >> .env
          echo "ALI_API_KEY=${{secrets.ALI_LLM_API_KEY}}" >> .env
          ls

      - name: Setup uv
        uses: astral-sh/setup-uv@v6.4.3
        with:
          version: latest
          activate-environment: true # 激活虚拟环境
          working-directory: . # 项目根目录

      - name: Run translation
        run: |
          uv sync --frozen
          uv run main.py -d ${{vars.DOCS_DIR}}  --incremental --auto-commit --auto-push
